spring:
  application:
    name: review-service
  datasource:
#    url: jdbc:h2:mem:test
#  h2: # http://localhost:8080/h2-console/
#    console:
#      enabled: true
    url: jdbc:postgresql://localhost:5432/k8app-review
    username: johnuser
    password: johnpwd
    driver-class-name: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update #create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          lob:
            non_contextual_creation: true

# ---------------- Logging
logging:
  file:
    path: /tmp/logs
  config: classpath:logback-spring.xml

# ---------------- Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health: # configurazione di /health
      show-details: always # never --- never e' l'opposto per non rendere visibili le informazioni
    shutdown:
      enabled: true #abilita lo shutdown by actuator
  info: # per vedere le /info
    env:
      enabled: true
  tracing: # Zipkin
    sampling:
      probability: 1.0
      endpoint: http://localhost:9411/api/v2/spans # questo e' il default, potrebbe essere omesso

server:
  shutdown: graceful
  port: 8083

# ---------------- Info (per Actuator /info)
info:
  app:
    name: SpringBoot Microservices With SpringCloud K8s Docker
    description: Springboot Course
    version: 0.0.1

# ---------------- Eureka
eureka:
  client:
    registerWithEureka: true # perche' l'MS si deve registrare a Eureka
    fetchRegistry: true # per avere il fetch del registry
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # indirizzo del Registry Server


